import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-purple-600"}>
        <div className="flex w-full bg-purple-700 pl-24 pt-8 pb-8 pr-24">
          <h1 className="text-3xl font-bold text-white">Post APP</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
